kind: Namespace
apiVersion: v1
metadata:
  name: dolibarr
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dolibarr
  namespace: dolibarr
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/dolibarr
      sourceRef:
        kind: GitRepository
        name: civi-cloud
        namespace: flux-system
  timeout: 10m0s # Timed out once before dolibarr was ready. Increase timeout to be sure.
  values:
    dolibarr:
      adminPassword: {{ .Values.admin.password | quote }}
    ldap:
      enabled: true
      host: openldap.civi-sso.svc.cluster.local
      usersDn: {{ include "dn.users" . | quote }}
      groupsDn: {{ include "dn.groups" . | quote }}
      loginAttribute: uid
      admin: 
        login: {{ include "names.ldap_admin_dn" . }}
        password: {{ include "secrets.ldap_admin_pw" . }}
    smtp: {{ .Values.smtp | toYaml | nindent 6 }}
    domain: {{ .Values.domain }}
    org: {{ .Values.org | toYaml | nindent 6 }}
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: acme
      host: {{ printf "%s.%s" .Values.subdomains.dolibarr .Values.domain }}
      tls:
        enabled: true
