# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: dolibarr
# spec:
#   interval: 5m
#   chart:
#     spec:
#       chart: ./charts/dolibarr
#       sourceRef:
#         kind: GitRepository
#         name: self
#   timeout: 10m0s # Timed out once before dolibarr was ready. Increase timeout to be sure.
#   values:
#     ldap:
#       enabled: true
#       host: {{ include "get_sso_config" (dict "key" "ldap_host" "context" $) }}
#       usersDn: {{ include "get_sso_config" (dict "key" "ldap_users_dn" "context" $) }}
#       groupsDn: {{ include "get_sso_config" (dict "key" "ldap_groups_dn" "context" $) }}
#       loginAttribute: uid
#       admin: 
#         login: {{ include "get_sso_config" (dict "key" "ldap_admin_dn" "context" $) }}
#         password: {{ include "get_sso_config" (dict "key" "ldap_admin_pw" "context" $) }}
#     smtp: {{ .Values.smtp | toYaml | nindent 6 }}
#     domain: {{ .Values.domain }}
#     org: {{ .Values.org | toYaml | nindent 6 }}
#     ingress:
#       enabled: true
#       annotations:
#         cert-manager.io/cluster-issuer: acme
#       host: {{ include "get_hostname" (dict "service" "dolibarr" "context" $) }}
#       tls:
#         enabled: true
