kind: Namespace
apiVersion: v1
metadata:
  name: dolibarr
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dolibarr
  namespace: dolibarr
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/dolibarr
      sourceRef:
        kind: GitRepository
        name: civi-cloud
        namespace: flux-system
  values:
    ldap:
      enabled: true
      host: openldap.civi-sso.svc.cluster.local
      dn: {{ printf "ou=users,dc=%s" (.Values.domain | splitList "." | join ",dc=") }}
      loginAttribute: email
      admin: 
        login: {{ include "names.ldap_admin_dn" . }}
        password: {{ include "secrets.ldap_admin_pw" . }}
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: acme
      host: {{ printf "%s.%s" .Values.subdomains.dolibarr .Values.domain }}
      tls:
        enabled: true
