apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homer
spec:
  interval: 5m
  chart:
    spec:
      chart: homer
      version: '7.2.2'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  values:
    image:
      tag: "v22.06.1"
    ingress:
      main:
        {{ $host := include "get_hostname" (dict "service" "homer" "context" $) -}}
        {{- $url := printf "https://%s" $host -}}
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: acme
        hosts:
          - host: {{ $host }}
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - hosts:
              - {{ $host }}
            secretName: homer-cert
    persistence:
      config:
        enabled: true
    configmap:
      config:
        enabled: true
        data:
          config.yml: |
            title: {{ .Values.org.name | quote }}
            subtitle: "Cloud Homepage"
            logo: {{ .Values.org.logoURL }}
            connectivityCheck: true
            proxy:
              useCredentials: true
            services:
              - name: "Main Apps"
                icon: "fas fa-code-branch"
                items:
                  - name: "Dolibarr"
                    logo: https://upload.wikimedia.org/wikipedia/commons/6/67/Dolibarr_logo.png
                    tag: app
                    keywords: "members accounting projects tasks issues CRM mail"
                    url: {{ include "get_hostname" (dict "service" "dolibarr" "context" $) }}
                    target: _blank
                  - name: "Nextcloud"
                    logo: https://upload.wikimedia.org/wikipedia/commons/6/60/Nextcloud_Logo.svg
                    tag: app
                    keywords: "files documents calendar contacts tasks mail polls forms"
                    url: {{ include "get_hostname" (dict "service" "nextcloud" "context" $) }}
                    target: _blank
                  - name: "Wordpress"
                    logo: https://upload.wikimedia.org/wikipedia/commons/2/20/WordPress_logo.svg
                    tag: app
                    keywords: "website blog"
                    url: {{ include "get_hostname" (dict "service" "wordpress" "context" $) }}
                    target: _blank
                  - name: "Jitsi"
                    logo: https://upload.wikimedia.org/wikipedia/commons/5/5d/Logo_Jitsi.svg
                    tag: app
                    keywords: "videochat conferencing meeting"
                    url: {{ include "get_hostname" (dict "service" "jitsi" "context" $) }}
                    target: _blank
                  - name: "Discourse"
                    logo: https://upload.wikimedia.org/wikipedia/commons/c/cf/Discourse_logo.svg
                    tag: app
                    keywords: "forum discussion community"
                    url: {{ include "get_hostname" (dict "service" "discourse" "context" $) }}
                    target: _blank
                  