apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud-aio
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/nextcloud-aio
      sourceRef:
        kind: GitRepository
        name: self
  dependsOn:
    - name: sso-clients
  values:
    ssoConfig:
      secretName: {{ .Values.ssoConfig.secretName }}
      namespace: {{ .Values.ssoConfig.namespace }}
    oidcClient:
      id: civi-oidc
      secretName: civi-oidc-client
    smtp: {{ .Values.smtp | toYaml | nindent 6 }}
    org: {{ .Values.org | toYaml | nindent 6 }}
    hostname: {{ include "get_hostname" (dict "service" "nextcloud" "context" $) }}
