
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: self
spec:
  interval: 5m0s
  url: {{ .Values.repo.url }}
  ref:
    branch: {{ .Values.repo.branch }}
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: domain-sso
spec:
  interval: 5m0s
  url: https://github.com/lorenzo-w/domain-sso
  ref:
    branch: main
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
spec:
  interval: 10m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: k8s-at-home
spec:
  interval: 10m
  url: https://k8s-at-home.com/charts/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rocketchat-server
spec:
  interval: 10m
  url: https://rocketchat.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jitsi
spec:
  interval: 10m
  url: https://jitsi-contrib.github.io/jitsi-helm/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: open-8gears
spec:
  interval: 10m
  url: https://8gears.container-registry.com/chartrepo/library/
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nextcloud
spec:
  interval: 10m
  url: https://nextcloud.github.io/helm/
