apiVersion: v1
kind: Secret
metadata:
  name: civi-oidc-client
type: Opaque
data:
  secret: {{ include "common.secrets.passwords.manage" (dict "secret" "civi-oidc-client" "key" "secret" "providedValues" (list "") "context" $) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: civi-saml-client
type: kubernetes.io/tls
data:
  {{ $saml_cert := dict "tls.crt" "" "tls.key" "" -}}
  {{- if not (include "common.secrets.exists" (dict "secret" "civi-saml-client" "context" $)) -}}
  {{- $gen_cert := genSelfSignedCert .Values.domain nil nil 3650 -}}
  {{- $_ := set $saml_cert "tls.crt" ($gen_cert.Cert | replace "\n" "" | trimPrefix "-----BEGIN CERTIFICATE-----" | trimSuffix "-----END CERTIFICATE-----" | b64enc) -}}
  {{- $_ := set $saml_cert "tls.key" ($gen_cert.Key | replace "\n" "" | trimPrefix "-----BEGIN RSA PRIVATE KEY-----" | trimSuffix "-----END RSA PRIVATE KEY-----" | b64enc) -}}
  {{- else -}}
  {{- $saml_cert = (lookup "v1" "Secret" .Release.Namespace "civi-saml-client").data -}}
  {{- end -}}
  tls.crt: {{ index $saml_cert "tls.crt" }}
  tls.key: {{ index $saml_cert "tls.key" }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sso-clients
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/connector
      sourceRef:
        kind: GitRepository
        name: domain-sso
  values:
    ssoProviderNamespace: {{ .Values.ssoConfig.namespace }}
    configSecretName: {{ .Values.ssoConfig.secretName }}
    clients:
      oidc:
        - id: civi-oidc
          redirectURIs:
            - {{ printf "https://%s/apps/oidc_login/oidc" (include "get_hostname" (dict "service" "nextcloud" "context" $)) }}
          secretName: civi-oidc-client
      saml:
        - id: {{ printf "https://%s/_saml/metadata/rocketchat-saml" (include "get_hostname" (dict "service" "rocketchat" "context" $)) }}
          certSecretName: civi-saml-client
          rootURL: {{ printf "https://%s" (include "get_hostname" (dict "service" "rocketchat" "context" $)) }}
          assertionConsumer: 
            method: post
            url: /_saml/validate/civi-saml
          logoutService:
            method: redirect
            url: /_saml/logout/civi-saml/
        - id: {{ printf "https://%s/wp-content/plugins/miniorange-saml-20-single-sign-on/" (include "get_hostname" (dict "service" "wordpress" "context" $)) }}
          rootURL: {{ printf "https://%s" (include "get_hostname" (dict "service" "wordpress" "context" $)) }}
          assertionConsumer: 
            method: post
            url: /
