sso:
  secretName: "" # Name of the secret containing all SSO config values
  namespace: "" # Namespace of the secret

oidcClient:
  id: ""
  secretName: ""

samlClients:
  ids: {}
  secretName: ""

smtp:
  host: ""
  port: ""
  senderAddress: ""
  login: ""
  password: ""
  tlsMode: "ssl/tls" # Alternatives: starttls, none

s3:
  endpoint: "" # Domain without protocol of your S3 endpoint (e.g. "s3.example.org")
  region: "eu-central-1" # Required by Longhorn, just leave the default if you don't have zones
  buckets:
    nextcloud: ""
    rocketchat: ""
  access_key:
    id: "" # Your S3 access key id
    secret: "" # Your S3 access key secret

org:
  name: ""
  defaultLocale: "en_US"

hostnames: {}

settings: {}
