admin:
  idp:
    # See https://dexidp.io/docs/connectors/
    type: "github"
    clientID: ""
    clientSecret: ""
    issuerURL: ""
  group: "" # A label identifying the group provided by your IDP, which is to be granted admin privileges (org:team for GitHub)
  email: "" # Admin email address (for email notifications)

domain: "" # The public root domain of this cluster (e.g. "example.org")

subdomains:
  # Under which subdomains of your supplied root domain should the various services run? (Created automatically by external-dns)
  keycloak: "idp"
  homer: "home"
  dolibarr: "orga"
  nextcloud: "cloud"
  onlyoffice: "office"
  rocketchat: "chat"
  jitsi: "meet"
  wordpress: "cms"
  frontity: "front"
  mautic: "pr"
  discourse: "forum"
  mobilizon: "events"
  n8n: "flows"
  blink: "link"
  elasticsearch: "search"

settings:
  frontity:
    embedded: true

repo:
  url: "https://github.com/lorenzo-w/civi-cloud"
  branch: "main"
