ssoConfig:
  secretName: "" # Name of the secret containing all SSO config values
  namespace: "" # Namespace of the secret

domain: "" # The public root domain of this cluster (e.g. "example.org")

org:
  name: "" # The full name of your organization
  defaultLocale: "en_US"
  logoURL: ""

smtp:
  host: ""
  port: ""
  senderAddress: ""
  login: ""
  password: ""
  tlsMode: "ssl/tls" # Alternatives: starttls, none

subdomains:
  # Under which subdomains of your supplied root domain should the various services run? (Created automatically by external-dns)
  homer: "home"
  dolibarr: "orga"
  nextcloud: "cloud"
  onlyoffice: "office"
  rocketchat: "chat"
  jitsi: "meet"
  wordpress: "cms"
  frontity: "front"
  mautic: "pr"
  discourse: "forum"
  mobilizon: "events"
  n8n: "flows"
  blink: "link"
  elasticsearch: "search"

settings:
  frontity:
    embedded: true

repo:
  url: "https://github.com/lorenzo-w/civi-cloud"
  branch: "main"
