apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onlyoffice
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/onlyoffice
      sourceRef:
        kind: GitRepository
        name: self
  dependsOn:
    - name: nextcloud
  values:
    jwtSecret: {{ include "get_sso_config" (dict "key" "internal_oidc_client_secret" "context" $) | quote }}
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: acme
      host: {{ .Values.hostnames.onlyoffice }}
      tls:
        enabled: true