apiVersion: v1
kind: Secret
metadata:
  name: rocketchat-db
type: Opaque
data:
  mongodb-password: {{ include "common.secrets.passwords.manage" (dict "secret" "rocketchat-db" "key" "mongodb-password" "providedValues" (list "") "context" $) }}
  mongodb-rootPassword: {{ include "common.secrets.passwords.manage" (dict "secret" "rocketchat-db" "key" "mongodb-rootPassword" "providedValues" (list "") "context" $) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rocketchat-admin
type: Opaque
data:
  password: {{ include "common.secrets.passwords.manage" (dict "secret" "rocketchat-admin" "key" "password" "providedValues" (list "") "context" $) }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rocketchat
spec:
  interval: 5m
  chart:
    spec:
      chart: rocketchat
      version: '4.7.4'
      sourceRef:
        kind: HelmRepository
        name: rocketchat-server
  dependsOn:
    - name: sso-clients
  valuesFrom:
    - kind: Secret
      name: rocketchat-db
      valuesKey: mongodb-password
      targetPath: "mongodb.auth.password"
    - kind: Secret
      name: rocketchat-db
      valuesKey: mongodb-rootPassword
      targetPath: "mongodb.auth.rootPassword"
  values:
    {{ $host := .Values.hostnames.rocketchat -}}
    replicaCount: 2
    host: {{ $host }}
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: acme
        nginx.ingress.kubernetes.io/proxy-body-size: 4G
      tls:
        - hosts:
            - {{ $host }}
          secretName: rocketchat-cert
    mongodb:
      persistence:
        enabled: true
        size: 8Gi
    extraEnv: | 
      - name: OVERWRITE_SETTING_Site_Name
        value: {{ printf "%s Chat" .Values.org.name }}
      - name: ADMIN_USERNAME
        value: superadmin
      - name: ADMIN_PASS
        valueFrom:
          secretKeyRef:
            name: rocketchat-admin
            key: password
      - name: ADMIN_EMAIL
        value: {{ include "get_sso_config" (dict "key" "admin_email" "context" $) }}
        
      - name: E2E_Enable
        value: "true"
      
      - name: OVERWRITE_SETTING_Accounts_RegistrationForm
        value: Disabled
      - name: Accounts_RegistrationForm_LinkReplacementText
        value: ""
      - name: OVERWRITE_SETTING_Accounts_TwoFactorAuthentication_Enabled
        value: "false"
      # - name: OVERWRITE_SETTING_Accounts_ShowFormLogin
      #   value: "false"
      - name: OVERWRITE_SETTING_Accounts_AllowUsernameChange
        value: "false"
      - name: OVERWRITE_SETTING_Accounts_AllowEmailChange
        value: "false"
      - name: OVERWRITE_SETTING_Accounts_AllowPasswordChange
        value: "false"
      
      - name: OVERWRITE_SETTING_Show_Setup_Wizard
        value: completed

      - name: Accounts_OAuth_Custom_Keycloak
        value: "true"
      - name: Accounts_OAuth_Custom_Keycloak_url
        value: {{ include "get_sso_config" (dict "key" "oidc_issuer_url" "context" $) }}
      - name: Accounts_OAuth_Custom_Keycloak_token_path
        value: {{ include "get_sso_config" (dict "key" "oidc_token_path" "context" $) }}
      - name: Accounts_OAuth_Custom_Keycloak_identity_path
        value: {{ include "get_sso_config" (dict "key" "oidc_userinfo_path" "context" $) }}
      - name: Accounts_OAuth_Custom_Keycloak_authorize_path
        value: {{ include "get_sso_config" (dict "key" "oidc_auth_path" "context" $) }}
      - name: Accounts_OAuth_Custom_Keycloak_token_sent_via
        value: header
      - name: Accounts_OAuth_Custom_Keycloak_scope
        value: "openid profile groups email"
      - name: Accounts_OAuth_Custom_Keycloak_id
        value: civi-oidc
      - name: Accounts_OAuth_Custom_Keycloak_secret
        value: {{ (lookup "v1" "Secret" .Release.Namespace .Values.oidcClient.secretName).data.secret | b64dec | quote }}
      - name: Accounts_OAuth_Custom_Keycloak_login_style
        value: redirect
      - name: Accounts_OAuth_Custom_Keycloak_button_label_text
        value: {{ printf "%s Login" .Values.org.name | quote }}
      - name: Accounts_OAuth_Custom-Keycloak_username_field
        value: sub
      - name: Accounts_OAuth_Custom_Keycloak_email_field
        value: email
      - name: Accounts_OAuth_Custom_Keycloak_merge_users
        value: "true"

      - name: OVERWRITE_SETTING_FileUpload_Storage_Type
        value: Webdav
      - name: OVERWRITE_SETTING_FileUpload_Webdav_Upload_Folder_Path
        value: rocketchat-uploads
      - name: OVERWRITE_SETTING_FileUpload_Webdav_Server_URL
        value: {{ printf "https://%s/remote.php/dav/files/admin/" .Values.hostnames.nextcloud }}
      - name: OVERWRITE_SETTING_FileUpload_Webdav_Username
        value: admin
      - name: OVERWRITE_SETTING_FileUpload_Webdav_Password
        valueFrom:
          secretKeyRef:
            name: nextcloud-admin
            key: password

      - name: OVERWRITE_SETTING_SMTP_Protocol
        value: smtps
      - name: OVERWRITE_SETTING_SMTP_Host
        value: {{ .Values.smtp.host }}
      - name: OVERWRITE_SETTING_SMTP_Port
        value: {{ .Values.smtp.port | quote }}
      - name: OVERWRITE_SETTING_SMTP_Username
        value: {{ .Values.smtp.login | quote }}
      - name: OVERWRITE_SETTING_SMTP_Password
        value: {{ .Values.smtp.password | quote }}
      - name: OVERWRITE_SETTING_From_Email
        value: {{ .Values.smtp.senderAddress }}