kind: ConfigMap
apiVersion: v1
metadata:
  name: wordpress-autoconfig
data:
  setup.sh: |
    #!/bin/bash
    echo 'installing plugins...'
    for PLUGIN in $(cat plugins.txt); do
      echo "installing $PLUGIN"
      wp plugin install $PLUGIN --activate
    done
    echo 'installing plugins... done'
    echo 'loading options...'
    mapfile OPTIONS < options.txt
    for OPTION in $OPTIONS; do
      wp option update $OPTION
    done
    echo 'loading options... done'
    echo 'wordpress all set up.'
  plugins.txt: |
    broken-link-checker
    contact-form-7
    doliconnect
    duplicate-page
    faustwp
    matomo
    miniorange-saml-20-single-sign-on
    permalink-manager
    public-post-preview
    super-progressive-web-apps
    ultimate-addons-for-gutenberg
    wordpress-seo
    wp-discourse
    wp-graphql
    wp-phpmyadmin-extension
    wp-smushit
  options.txt: |
    saml_identity_name {{ printf "%s SSO" .Values.org.name | quote }}
    mo_saml_identity_provider_identifier_name {{ printf "%s SSO" .Values.org.name | quote }}
    saml_login_url {{ include "get_sso_config" (dict "key" "saml_entrypoint_url" "context" $) | quote }}
    saml_issuer {{ include "get_sso_config" (dict "key" "idp_url" "context" $) | quote }}
    saml_x509_certificate "s:997:\"a:1:{i:0;s:978:\"-----BEGIN CERTIFICATE-----{{ index (lookup "v1" "Secret" .Values.ssoConfig.namespace (include "get_sso_config" (dict "key" "idp_cert_secret" "context" $))).data "tls.crt" | b64dec }}-----END CERTIFICATE-----\";}\";"
    saml_am_default_user_role contributor
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db
type: Opaque
data:
  mariadb-password: {{ include "common.secrets.passwords.manage" (dict "secret" "wordpress-db" "key" "mariadb-password" "providedValues" (list "") "context" $) }}
  mariadb-root-password: {{ include "common.secrets.passwords.manage" (dict "secret" "wordpress-db" "key" "mariadb-root-password" "providedValues" (list "") "context" $) }}
  mariadb-replication-password: {{ include "common.secrets.passwords.manage" (dict "secret" "wordpress-db" "key" "mariadb-replication-password" "providedValues" (list "") "context" $) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-admin
type: Opaque
data:
  wordpress-password: {{ include "common.secrets.passwords.manage" (dict "secret" "wordpress-admin" "key" "wordpress-password" "providedValues" (list "") "context" $) }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
spec:
  interval: 5m
  chart:
    spec:
      chart: wordpress
      version: "14.3.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
  timeout: 10m0s # Increase timeout to be sure.
  dependsOn:
    - name: sso-clients
  values:
    ingress:
      enabled: true
      hostname: {{ .Values.hostnames.wordpress }}
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: acme
    wordpressUsername: admin
    wordpressEmail: {{ include "get_sso_config" (dict "key" "admin_email" "context" $) }}
    existingSecret: wordpress-admin
    wordpressBlogName: {{ .Values.org.name | quote }}
    wordpressScheme: https
    wordpressExtraConfigContent: | 
      define( 'WPLANG', {{ .Values.org.defaultLocale | quote }} );
    wordpressConfigureCache: true
    extraVolumes:
      - name: autoconfig
        configMap:
          name: wordpress-autoconfig
    extraVolumeMounts:
      - name: autoconfig
        mountPath: /autoconfig
        readOnly: true
    customPostInitScripts:
      autoconfig.sh: |
        #!/bin/bash
        cd /autoconfig
        bash ./setup.sh
    smtpHost: {{ .Values.smtp.host }}
    smtpPort: {{ .Values.smtp.port | quote }}
    smtpUser: {{ .Values.smtp.login | quote }}
    smtpPassword: {{ .Values.smtp.password | quote }}
    smtpProtocol: {{ .Values.smtp.tlsMode }}
    service:
      type: ClusterIP
    mariadb:
      enabled: true
      fullnameOverride: wordpress-db
      auth:
        database: wordpress
        username: wordpress
        existingSecret: wordpress-db
    memcached:
      enabled: true
