apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mariadb.auth.existingSecret }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "onlyoffice.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-password: {{ include "common.secrets.passwords.manage" (dict "secret" .Values.mariadb.auth.existingSecret "key" "mariadb-password" "providedValues" (list "mariadb.auth.password") "context" $) }}
  mariadb-root-password: {{ include "common.secrets.passwords.manage" (dict "secret" .Values.mariadb.auth.existingSecret "key" "mariadb-root-password" "providedValues" (list "mariadb.auth.rootPassword") "context" $) }}
  mariadb-replication-password: {{ include "common.secrets.passwords.manage" (dict "secret" .Values.mariadb.auth.existingSecret "key" "mariadb-replication-password" "providedValues" (list "mariadb.replicationPassword") "context" $) }}
