apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-config" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
      - name: mysql-client
        image: mysql
        command: ["mysql"]
        args:
          - {{ printf "--user=%s" .Values.mariadb.auth.username | quote }}
          - "--password=$(DB_PASSWORD)"
          - {{ printf "--host=%s" (include "mariadb.serviceHost" .) | quote }}
          - {{ printf "--port=%s" (toString .Values.mariadb.port) | quote }}
          - "--local-infile=1"
          - {{ .Values.mariadb.auth.database }}
          - "-e"
          - "SOURCE /doli/config.sql;"
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mariadb.auth.existingSecret }}
                key: mariadb-password
        volumeMounts:
          - name: config
            mountPath: "/doli"
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "dolibarr.cmName" . }}
      restartPolicy: Never
  backoffLimit: 4