apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dolibarr.fullname" . }}
  labels:
    {{- include "dolibarr.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dolibarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dolibarr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dolibarr.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: documents
        persistentVolumeClaim:
          claimName: {{ include "dolibarr.pvcName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /var/www/documents
            name: documents
          env:
            - name: DOLI_DB_HOST
              value: {{ include "mariadb.serviceHost" . }}
            - name: DOLI_DB_NAME
              value: {{ .Values.mariadb.auth.database }}
            - name: DOLI_DB_PORT
              value: {{ .Values.mariadb.port | quote }}
            - name: DOLI_DB_USER
              value: {{ .Values.mariadb.auth.username }}
            - name: DOLI_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mariadb.auth.existingSecret }}
                  key: mariadb-password
            - name: DOLI_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dolibarr.fullname" . }}
                  key: doli-admin-password
            - name: DOLI_MODULES
              value: {{ join "," .Values.dolibarr.modules | quote }}
            - name: DOLI_URL_ROOT
              value: {{ printf "http://%s" .Values.ingress.host | quote }}
            - name: DOLI_AUTH
              value: 
                {{- if .Values.ldap.enabled -}}
                  {{- "dolibarr,openid,ldap" | quote | indent 1 -}}
                  {{- else -}}
                  {{- "dolibarr,openid" | quote | indent 1 -}}
                {{- end }}
            - name: DOLI_PROD
              value: 
                {{- if .Values.dolibarr.prod -}}
                  {{- "1" | quote | indent 1 -}}
                  {{- else -}}
                  {{- "0" | quote | indent 1 -}}
                {{- end }}
            - name: DOLI_NO_CSRF_CHECK
              value: "1"
            - name: DOLI_LDAP_HOST
              value: {{ .Values.ldap.host }}
            - name: DOLI_LDAP_PORT
              value: {{ .Values.ldap.port | quote }}
            - name: DOLI_LDAP_DN
              value: {{ .Values.ldap.usersDn }}
            - name: DOLI_LDAP_LOGIN_ATTRIBUTE
              value: {{ .Values.ldap.loginAttribute }}
            - name: DOLI_LDAP_ADMIN_LOGIN
              value: {{ .Values.ldap.admin.login }}
            - name: DOLI_LDAP_ADMIN_PASS
              value: {{ .Values.ldap.admin.password }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
