apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dolibarr.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "dolibarr.labels" . | nindent 4 }}
type: Opaque
data:
  doli-admin-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "dolibarr.fullname" .) "key" "doli-admin-password" "providedValues" (list "dolibarr.adminPassword") "context" $) }}
