apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dolibarr.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "dolibarr.labels" . | nindent 4 }}
type: Opaque
data:
  doli-admin-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "dolibarr.fullname" .) "key" "doli-admin-password" "providedValues" (list "dolibarr.adminPassword") "context" $) }}
  doli-cron-secret: {{ include "common.secrets.passwords.manage" (dict "secret" (include "dolibarr.fullname" .) "key" "doli-cron-secret" "providedValues" (list "") "context" $) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: doli-db
  namespace: {{ .Release.Namespace }}
  labels: {{- include "dolibarr.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-password: {{ include "common.secrets.passwords.manage" (dict "secret" "doli-db" "key" "mariadb-password" "providedValues" (list "mariadb.auth.password") "context" $) }}
  mariadb-root-password: {{ include "common.secrets.passwords.manage" (dict "secret" "doli-db" "key" "mariadb-root-password" "providedValues" (list "mariadb.auth.rootPassword") "context" $) }}
  mariadb-replication-password: {{ include "common.secrets.passwords.manage" (dict "secret" "doli-db" "key" "mariadb-replication-password" "providedValues" (list "mariadb.replicationPassword") "context" $) }}
