apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      chart: nextcloud
      version: '2.14.3'
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  timeout: 10m0s # Increase timeout to be sure.
  dependsOn:
    - name: sso-clients
  valuesFrom:
    - kind: Secret
      name: nextcloud-admin
      valuesKey: password
      targetPath: "nextcloud.password"
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: acme
      tls:
        - secretName: nextcloud-tls
          hosts:
            - {{ .Values.hostname }}
    nextcloud:
      host: {{ .Values.hostname }}
      username: admin
      mail:
        enabled: true
        fromAddress: {{ .Values.smtp.senderAddress }}
        # domain: "?"
        smtp:
          host: {{ .Values.smtp.host }}
          port: {{ .Values.smtp.port }}
          secure: {{ if eq .Values.smtp.tlsMode "ssl" -}}
            "ssl"
            {{- else -}}
            "starttls"
          {{- end }}
          name: {{ .Values.smtp.login }}
          password: {{ .Values.smtp.password }}
      configs:
        oidc.config.php: | 
          <?php
          $CONFIG = array (
            // See here for explanation: https://github.com/pulsejet/nextcloud-oidc-login#config
            'allow_user_to_change_display_name' => false,
            'lost_password_link' => 'disabled',
            'oidc_login_provider_url' => {{ include "get_sso_config" (dict "key" "oidc_issuer_url" "context" $) | quote }},
            'oidc_login_client_id' => {{ .Values.oidcClient.id | quote }},
            'oidc_login_client_secret' => {{ (lookup "v1" "Secret" .Release.Namespace .Values.oidcClient.secretName).data.secret | quote }},
            'oidc_login_auto_redirect' => true,
            'oidc_login_end_session_redirect' => false,
            'oidc_login_default_quota' => '1000000000',
            'oidc_login_button_text' => 'Log in with OpenID',
            'oidc_login_hide_password_form' => false,
            'oidc_login_use_id_token' => false,
            'oidc_login_attributes' => array (
                'id' => 'sub',
                'name' => 'name',
                'mail' => 'email',
                'quota' => 'ownCloudQuota',
                'home' => 'homeDirectory',
                'ldap_uid' => 'uid',
                'groups' => 'ownCloudGroups',
                'photoURL' => 'picture',
                'is_admin' => 'ownCloudAdmin',
            ),
            'oidc_login_default_group' => 'oidc',
            'oidc_login_use_external_storage' => false,
            'oidc_login_scope' => 'openid profile groups email',
            'oidc_login_proxy_ldap' => false,
            'oidc_login_disable_registration' => false,
            'oidc_login_redir_fallback' => false,
            'oidc_login_tls_verify' => true,
            'oidc_create_groups' => true
          );
          ?>
        locale.config.php: | 
          <?php
          $CONFIG = array (
            'default_locale' => {{ .Values.org.defaultLocale | quote }},
          );
          ?>
      extraVolumes:
        - name: autoconfig
          configMap:
            name: nextcloud-autoconfig
      extraVolumeMounts:
        - name: autoconfig
          mountPath: /autoconfig
          readOnly: true
    # lifecycle:
    #   postStart:
    #     exec:
    #       command: ["/bin/sh", "-c", "cd /autoconfig & ./setup.sh"]
    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: mysql
      host: {{ printf "%s.%s.svc.cluster.local" "nextcloud-db" .Release.Namespace }}
      user: nextcloud
      existingSecret:
        enabled: true
        secretName: nextcloud-db
        usernameKey: mariadb-username
        passwordKey: mariadb-password
    mariadb:
      enabled: true
      auth:
        database: nextcloud
        existingSecret: nextcloud-db
      primary:
        persistence:
          enabled: true
    cronjob:
      enabled: true
    persistence:
      enabled: true
