apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onlyoffice
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/onlyoffice
      sourceRef:
        kind: GitRepository
        name: self
  dependsOn:
    - name: nextcloud