apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db
type: Opaque
data:
  mariadb-password: {{ include "common.secrets.passwords.manage" (dict "secret" "nextcloud-db" "key" "mariadb-password" "providedValues" (list "") "context" $) }}
  mariadb-root-password: {{ include "common.secrets.passwords.manage" (dict "secret" "nextcloud-db" "key" "mariadb-root-password" "providedValues" (list "") "context" $) }}
  mariadb-replication-password: {{ include "common.secrets.passwords.manage" (dict "secret" "nextcloud-db" "key" "mariadb-replication-password" "providedValues" (list "") "context" $) }}
  db-username: {{ "nextcloud" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-admin
type: Opaque
data:
  password: {{ include "common.secrets.passwords.manage" (dict "secret" "nextcloud-admin" "key" "password" "providedValues" (list "") "context" $) }}